name: "Create :: Node CICD"

on:
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  #######################################################################
  #                          BUMP VERSION                               #
  #######################################################################
  validate:
    name: "Validation"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18.x
          # - 20.x
          # - 21.x
          # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        language:
          - js
          # - ts
          # - coffee
        targets:
          - all
          # - browser
          # - deno
          # - node-cjs
          # - node-esm
        package-manager:
          - npm
          # - pnpm
          # - yarn
        test-framework:
          # - ava
          # - jasmine
          - jest
          # - mocha
          # - vitest
        build-tool:
          - ""
          # - esbuild
          # - rollup
          # - swc
          # - parcel # web bundler
          # - rolldown # not mature yet
          # - snowpack # who is this guy?
          # - turbpack # not mature yet
          # - vite # web bundler, using esbuild and roll*
          # - webpack # web bundler using babel and roll*
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Init
        run: |
          npm i
          if [ "${{ matrix.package-manager }}" != "" ]; then
            npm i -g ${{ matrix.package-manager }}
          fi
      - name: Init Project
        run: |
          CREATE_ARGS=""
          if [ "${{ matrix.build-tool }}" != "" ]; then
            CREATE_ARGS="--build-tool ${{ matrix.build-tool }}"
          fi
          SKIP_NPM_INIT=1 node ./packages/create-node/src/index.js /tmp/test-node $CREATE_ARGS \
            --language ${{ matrix.language }} \
            --targets ${{ matrix.targets }} \
            --package-manager ${{ matrix.package-manager }} \
            --test-framework ${{ matrix.test-framework }} \
            $CREATE_ARGS

          npm run build -w @templ-project/create-node
      - name: Validate Project
        if: ${{ matrix.language != 'ts' && matrix.test-framework != 'mocha' }}
        run: |
          project_path=$(pwd)
          cd /tmp/test-node \
            && cat package.json \
            && npm i \
            && npm i -S $project_path --legacy-peer-deps \
            && ${{ matrix.package-manager }} run ca \
            && ${{ matrix.package-manager }} run test \
            && ${{ matrix.package-manager }} run build
