name: "Create :: Node CICD"

on:
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  #######################################################################
  #                          BUMP VERSION                               #
  #######################################################################
  validate:
    name: "Validation"
    strategy:
      matrix:
        node-version:
          - 18.x
        language:
          - js
          - ts
        targets:
          - all
        package-manager:
          - npm
        test-framework:
          - jest
          - vitest
        build-tool:
          - ""
          - esbuild
          - rollup
          - swc
    uses: templ-project/create/.github/workflows/create-node-single.yml@main
    secrets: inherit
    with:
      BuildTools: "${{ matrix.build-tool }}"
      Language: "${{ matrix.language }}"
      PackageManager: "${{ matrix.package-manager }}"
      Targets: "${{ matrix.targets }}"
      TestFramework: "${{ matrix.test-framework }}"
      UseDefaultCommand: true
