name: "Create :: Node CICD"

on:
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  #######################################################################
  #                          BUMP VERSION                               #
  #######################################################################
  validate:
    name: "Validation"
    strategy:
      matrix:
        node-version:
          - 18.x
        language:
          - js
          - ts
          # - coffee
        targets:
          - all
          - browser
          - node-cjs
          - node-esm
        package-manager:
          - npm
        test-framework:
          - jest
          - vitest
        build-tool:
          - ""
          - esbuild
          - rollup
          - swc
          # - parcel # web bundler
          # - rolldown # not mature yet
          # - snowpack # who is this guy?
          # - turbpack # not mature yet
          # - vite # web bundler, using esbuild and roll*
          # - webpack # web bundler using babel and roll*
    uses: templ-project/create/.github/workflows/create-node-single.yml@main
    secrets: inherit
    with:
      BuildTools: "${{ matrix.build-tool }}"
      Language: "${{ matrix.language }}"
      PackageManager: "${{ matrix.package-manager }}"
      Targets: "${{ matrix.targets }}"
      TestFramework: "${{ matrix.test-framework }}"
      UseDefaultCommand: true
